//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYUSIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        public int StudentExamID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> LecturerID { get; set; }
        public Nullable<int> ExamOne { get; set; }
        public Nullable<int> ExamTwo { get; set; }
        public Nullable<int> ExamFinal { get; set; }
        public Nullable<int> Homework { get; set; }
        public Nullable<int> Project { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual Student Student { get; set; }
    }
}
