//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYUSIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourse
    {
        public int StudentCourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> LecturerID { get; set; }
        public string Classroom { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> StartingTimeID { get; set; }
        public Nullable<int> FinishTimeID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Day Day { get; set; }
        public virtual FinishTime FinishTime { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual StartingTime StartingTime { get; set; }
        public virtual Student Student { get; set; }
    }
}
